typography_spectrum: 0.8355685316491872
color:
  brandStrength: 0.6024315257091075
  lightness: 0.738469586474821
  saturation: 0.6780581788625568
  rhythmicContrast: 0.5313768910709769
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
opengraph:
  type: 'https://www.facebook.com/garyjaron'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/020c9877-841d-4ce4-a0a5-c94b3d79edf2.jpg
layout_spectrum: 0.49050882342271507
author:
  name: Gary M Jaron
  email: grayravensf@gmail.com
  url: 'https://independent.academia.edu/GaryJaron'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9fcb971e-34c9-432e-8f4f-fdf8f05df68d.jpg
name: Find Your Way
title: 'A Pragmatic Orienting Philosophic System '
