typography_spectrum: 0.7602588564623147
color:
  brandStrength: 0.4074821835383773
  lightness: 0.9059438009280711
  saturation: 0.0221587426494807
  rhythmicContrast: 0.7176319335121661
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
opengraph:
  type: 'https://www.facebook.com/garyjaron'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/020c9877-841d-4ce4-a0a5-c94b3d79edf2.jpg
layout_spectrum: 0.10741678928025067
author:
  name: Gary M Jaron
  email: grayravensf@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/74cabf7f-39da-4bbe-b829-96e81b93d7a8.jpg
name: Find Your Way
title: Philosophy
