typography_spectrum: 0.8355685316491872
color:
  brandStrength: 0.6024315257091075
  lightness: 0.738469586474821
  saturation: 0.6780581788625568
  rhythmicContrast: 0.5313768910709769
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
opengraph:
  type: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/020c9877-841d-4ce4-a0a5-c94b3d79edf2.jpg
  appId: 'https://www.facebook.com/garyjaron'
layout_spectrum: 0.49050882342271507
analytics:
  google: UA-81696929-1
author:
  name: Gary M Jaron
  email: grayravensf@gmail.com
  url: 'https://independent.academia.edu/GaryJaron'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9fcb971e-34c9-432e-8f4f-fdf8f05df68d.jpg
name: Find Your Way
navigation:
  - name: Find Your Way By Gary M. Jaron
    id: f6a660e3-3f36-4358-bc0c-842d759915ef
    type: content
  - name: ‘Not all those who wander '
    id: 7ae0d620-e3b9-47fd-ba69-1c9a6ff90ee6
    type: content
  - name: The Unexamined Life
    id: e814ee6f-164c-4385-9e1d-f511c74597d3
    type: content
  - name: The word is not the thing.
    id: 202979bf-1ede-4221-b896-f895c981ef27
    type: content
  - name: Maps and the Territory
    id: 0349a9eb-93e7-4ec6-a577-5b602c59a5ea
    type: content
  - name: True Tao? True Name?
    id: 46f3e198-c8f1-49eb-9bdc-4fab9efbd1b5
    type: content
  - name: Korzbski on words and things
    id: b450f9d0-a77f-4eaa-8da5-0537145b82c2
    type: content
  - name: The Measure of all things
    id: ec416ea0-191a-4b47-8623-234b052f8f3f
    type: content
  - name: 'Excerpt # 1 from Zen and the Art'
    id: 53311f7f-b182-4732-9726-11d7eaa2d0f5
    type: content
  - name: James on Pragmatism
    id: 6904afe5-2e15-4c33-b30a-6c4d7344997b
    type: content
  - name: Guidebooks
    id: f739ce58-0a51-4cb4-a45d-2c20ae703eb4
    type: content
  - name: Religion is a metaphor
    id: e8dc8b5f-d14e-476b-9c2f-ccc2b3dec5fe
    type: content
title: 'A Pragmatic Orienting Philosophic System '
