typography_spectrum: 0.8355685316491872
color:
  brandStrength: 0.6024315257091075
  lightness: 0.738469586474821
  saturation: 0.6780581788625568
  rhythmicContrast: 0.5313768910709769
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
opengraph:
  type: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/020c9877-841d-4ce4-a0a5-c94b3d79edf2.jpg
  appId: 'https://www.facebook.com/garyjaron'
layout_spectrum: 0.49050882342271507
analytics:
  google: UA-81696929-1
author:
  name: Gary M Jaron
  email: grayravensf@gmail.com
  url: 'https://independent.academia.edu/GaryJaron'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9fcb971e-34c9-432e-8f4f-fdf8f05df68d.jpg
name: Find Your Way
navigation:
  - name: Find Your Way By Gary M. Jaron
    id: f6a660e3-3f36-4358-bc0c-842d759915ef
    type: content
  - name: ‘Not all those who wander '
    id: 7ae0d620-e3b9-47fd-ba69-1c9a6ff90ee6
    type: content
  - name: The word is not the thing.
    id: 202979bf-1ede-4221-b896-f895c981ef27
    type: content
  - name: Maps and the Territory
    id: 0349a9eb-93e7-4ec6-a577-5b602c59a5ea
    type: content
title: 'A Pragmatic Orienting Philosophic System '
