typography_spectrum: 0.8118161452527499
color:
  brandStrength: 0.4802821945829667
  lightness: 0.9412634877636475
  saturation: 0.006361750505477337
  rhythmicContrast: 0.8402614391534267
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
github: true
opengraph:
  type: home page
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/020c9877-841d-4ce4-a0a5-c94b3d79edf2.jpg
  appId: 'https://www.facebook.com/garyjaron'
layout_spectrum: 0.7546202465154157
analytics:
  google: UA-81696929-1
author:
  name: Gary M Jaron
  email: grayravensf@gmail.com
  url: 'https://independent.academia.edu/GaryJaron'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/189e5d04-96db-4b12-b750-96182c02129d.jpg
name: Find Your Way
navigation:
  - name: 'Read this first: A Guide to this blog site'
    id: a9a439b6-60e1-45ec-b4a5-c6c2d2beee17
    type: content
  - name: Blog 1)Why I updated this site on Sept 9 2016
    id: f857d3ea-c342-4308-8978-692af10abb92
    type: content
  - name: Blog 2) a map to future posts
    id: f6a660e3-3f36-4358-bc0c-842d759915ef
    type: content
  - name: Blog 3) Who is Alfred Korzybski and why should I care?
    id: 5e4178de-7190-4329-8137-669ad610b28a
    type: content
  - name: 'Blog 4) Bias: the shaping influence of ideas and experienece'
    id: 449c8686-8a6d-4128-8079-05296ed3fe4a
    type: content
  - name: Blog 5) Poincare and bias and shaping ideas
    id: 14837bf9-96b3-4daf-8af1-61563e3e52e0
    type: content
  - name: 'Blog 6) Where bias comes from: Neural Beings Must Categorize'
    id: 74416eab-8e8b-49c1-a33f-f4d2c6bc5e2f
    type: content
  - name: Blog 7) Pragmatic Wisdom
    id: f9d8fb87-3af9-4595-bbf6-06375ff9626e
    type: content
  - name: Blog 8) William James and why you should know something about him.
    id: 7871c60a-4137-4d15-9b2e-f9725627e2f2
    type: content
  - name: Blog 9) What is a pragmatic orienting system?
    id: 099176eb-3e3a-491f-9b13-ccc6705b9caa
    type: content
  - name: Blog 10) How we biologically make maps of the Territory
    id: 2bf3b48e-3b62-47cd-9913-852c1d837678
    type: content
  - name: Contact info
    id: ddd705cf-500e-4298-baec-7b6bb3def78d
    type: content
  - name: 'Jarons and Jermanoks: It’s a family thing….'
    id: 636895ce-040a-4542-b066-ae5ed3a01c00
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0041de3e-259b-4356-b756-de2f328323ef.jpg
title: Gary Jaron_Find Your Way
content: []
description: Gary Jaron's blog
purpose:
  - type: contact
    url: 'mailto:gmjaron@uw.edu'
    label: Contact me
  - type: external
    url: 'https://www.facebook.com/garyjaron'
    label: Gary Jaron Facebook page
