layout_spectrum: 0.9379903515800834
typography_spectrum: 0.1996176578104496
color:
  brandStrength: 0.6024315257091075
  lightness: 0.738469586474821
  saturation: 0.6780581788625568
  rhythmicContrast: 0.5313768910709769
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
opengraph:
  type: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/020c9877-841d-4ce4-a0a5-c94b3d79edf2.jpg
  appId: 'https://www.facebook.com/garyjaron'
analytics:
  google: UA-81696929-1
author:
  name: Gary M Jaron
  email: grayravensf@gmail.com
  url: 'https://www.facebook.com/garyjaron'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9fcb971e-34c9-432e-8f4f-fdf8f05df68d.jpg
name: Find Your Way
navigation:
  - name: find your way intro
    id: f6a660e3-3f36-4358-bc0c-842d759915ef
    type: content
  - name: what is a pragmatic orienting system?
    id: 099176eb-3e3a-491f-9b13-ccc6705b9caa
    type: content
  - name: Korzybski on words and structure
    id: 8aace2ea-d6a4-41b9-bc33-2072c3524f34
    type: content
  - name: 'Korzybski: Maps and the Territory'
    id: 094541d6-c0b4-497a-91f2-7e0861d13f3b
    type: content
  - name: James on pragmatic truth
    id: 7871c60a-4137-4d15-9b2e-f9725627e2f2
    type: content
  - name: 'Pirsig on the analytic knife (ZMM excerpt #1)'
    id: 53311f7f-b182-4732-9726-11d7eaa2d0f5
    type: content
  - name: See some of my posted papers at Academia.edu
    id: 1d77ba8f-0b71-4b5f-8932-c99ac8a90e99
    type: content
title: Gary Jaron's Blog
description: Find Your Way
