typography_spectrum: 0.8118161452527499
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.4802821945829667
  lightness: 0.9412634877636475
  saturation: 0.006361750505477337
  rhythmicContrast: 0.8402614391534267
github: true
opengraph:
  type: home page
  appId: 'https://www.facebook.com/garyjaron'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/020c9877-841d-4ce4-a0a5-c94b3d79edf2.jpg
layout_spectrum: 0.7546202465154157
analytics:
  google: UA-81696929-1
author:
  name: Gary M Jaron
  url: 'https://independent.academia.edu/GaryJaron'
  email: grayravensf@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/189e5d04-96db-4b12-b750-96182c02129d.jpg
name: Find Your Way
url: 'https://garyjaron.com'
navigation:
  - name: 'Read this first: A Guide to this blog site'
    id: a9a439b6-60e1-45ec-b4a5-c6c2d2beee17
    type: content
  - name: Blog 1)Why I updated this site on Sept 9 2016
    id: f857d3ea-c342-4308-8978-692af10abb92
    type: content
  - name: Blog 2) a map to future posts
    id: f6a660e3-3f36-4358-bc0c-842d759915ef
    type: content
  - name: Blog 3) Who is Alfred Korzybski and why should I care?
    id: 5e4178de-7190-4329-8137-669ad610b28a
    type: content
  - name: 'Blog 4) Bias: the shaping influence of ideas and experienece'
    id: 449c8686-8a6d-4128-8079-05296ed3fe4a
    type: content
  - name: Blog 5) Poincare and bias and shaping ideas
    id: 14837bf9-96b3-4daf-8af1-61563e3e52e0
    type: content
  - name: 'Blog 6) Where bias comes from: Neural Beings Must Categorize'
    id: 74416eab-8e8b-49c1-a33f-f4d2c6bc5e2f
    type: content
  - name: Blog 7) Pragmatic Wisdom
    id: f9d8fb87-3af9-4595-bbf6-06375ff9626e
    type: content
  - name: Blog 8) William James and why you should know something about him.
    id: 7871c60a-4137-4d15-9b2e-f9725627e2f2
    type: content
  - name: Blog 9) What is a pragmatic orienting system?
    id: 099176eb-3e3a-491f-9b13-ccc6705b9caa
    type: content
  - name: Blog 10) How we biologically make maps of the Territory
    id: 2bf3b48e-3b62-47cd-9913-852c1d837678
    type: content
  - name: Blog 11) William James On the Biology of Mind
    id: 6b0e81c3-e1c2-4406-9317-20b8c6720952
    type: content
  - name: Contact info
    id: ddd705cf-500e-4298-baec-7b6bb3def78d
    type: content
  - name: 'Jarons and Jermanoks: It’s a family thing….'
    id: 636895ce-040a-4542-b066-ae5ed3a01c00
    type: content
  - name: Timeline 2000 BCE- 1 CE
    id: 668fb842-6358-479a-b26c-299713e4ab95
    type: content
  - name: A Timeline 1 CE - 900 CE
    id: ff0c2202-d88e-4ddf-8ae3-99bf26326282
    type: content
  - name: Timeline 1000-1100 CE
    id: 1c76f1ce-04cc-40f4-b535-fd035bfa3237
    type: content
  - name: Timeline 1200-1300 CE
    id: 351776d2-f705-42fa-a96e-22d8c6d8b3ed
    type: content
  - name: Timeline 1400's CE
    id: f0233f7a-4504-4944-afd2-b84e77e345c4
    type: content
  - name: Timeline 1500's CE
    id: 36b45054-6b87-4694-a85a-1449ed612443
    type: content
  - name: Timeline 1600's CE
    id: 188c4138-7432-4de6-8c8b-d6652b48e87b
    type: content
  - name: Timeline 1700's CE
    id: a4cdc8b3-f757-4238-acb1-8739e04ee6e0
    type: content
  - name: Timeline 1800's CE
    id: 7cfcd405-dcaa-46f7-86d2-5f9cbc497c56
    type: content
  - name: Timeline 1900-1940 CE
    id: 16b46111-4824-4102-8456-c7972410b891
    type: content
  - name: Blog 12) Reality of Everyday Life
    id: 7e7a4930-2dbc-4115-a02e-4c4e618dd431
    type: content
  - name: 'Blog 13) Bond, James Bond'
    id: ff3e205b-c58a-44ac-bb8c-68def827acc5
    type: content
  - name: Blog 14) Maps of the Territory built upon the fact of birth and death
    id: 5af9d35c-0c6e-413d-8ee7-5fdaa9e05810
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0041de3e-259b-4356-b756-de2f328323ef.jpg
title: Gary Jaron_Find Your Way
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f52ad2b4-a6f2-4f9d-967d-6656edd0e084.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f52ad2b4-a6f2-4f9d-967d-6656edd0e084.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Gary Jaron's blog
purpose:
  - type: contact
    url: 'mailto:gmjaron@uw.edu'
    label: Contact me
  - type: external
    url: 'https://www.facebook.com/garyjaron'
    label: Gary Jaron Facebook page
